let dataMovies=[
    //Action Movies 
    {
        id: Math.random(),
        title: "The Marvels",
        image:
        "https://image.tmdb.org/t/p/w342/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
        rate: 6.3,
        decr: "Carol Danvers, aka Captain Marvel, has reclaimed her identity from the tyrannical Kree and taken revenge on the Supreme Intelligence. But unintended consequences see Carol shouldering the burden of a destabilized universe. When her duties send her to an anomalous wormhole linked to a Kree revolutionary, her powers become entangled with that of Jersey City super-fan Kamala Khan, aka Ms. Marvel, and Carol’s estranged niece, now S.A.B.E.R. astronaut Captain Monica Rambeau. Together, this unlikely trio must team up and learn to work in concert to save the universe.",
        Starring:"Brie Larson, Teyonah Parris, Iman Vellani, Zawe Ashton, Samuel L. Jackson, Gary Lewis, Park Seo-jun, Zenobia Shroff, Mohan Kapur, Saagar Shaikh",
        stream:"https://www.youtube.com/embed/wS_qbDztgVY" ,
        lang: "EN",
        genre: "action",
        downlaod: "https://stellaruranus.com/?utm_medium=Special_Interest&utm_source=easyaffiliate&utm_campaign=1076&utm_content=LandingPage_Classic_Keyword&emid=65cb65b195182508e7088ba3&trs=65cb65b195182508e7088ba2&ext_publisher_id=1076&fn=The+Marvels+%5B1019+Mo%5D",
        Directed:"Nia DaCosta",
        year:"2023",
        dure:"105m"
    }, 
    {
        id: Math.random(),
        title: " The Beekeeper",
        image:
        "https://image.tmdb.org/t/p/w342/A7EByudX0eOzlkQ2FIbogzyazm2.jpg",
        rate: 7.3,
        decr: "One man's campaign for vengeance takes on national stakes after he is revealed to be a former operative of a powerful and clandestine organization known as Beekeepers.",
        Starring:"Jason Statham, Emmy Raver-Lampman, Bobby Naderi, Josh Hutcherson, Jeremy Irons, Taylor James, Phylicia Rashād, Jemma Redgrave, Minnie Driver, Sophia Feliciano",
        stream:"https://youtu.be/SzINZZ6iqxY?t=1" ,
        lang: "EN",
        genre: "action",
        downlaod: "https://stellaruranus.com/?utm_medium=Special_Interest&utm_source=easyaffiliate&utm_campaign=1076&utm_content=LandingPage_Classic_Keyword&emid=65cb65b195182508e7088ba3&trs=65cb65b195182508e7088ba2&ext_publisher_id=1076&fn=The+Marvels+%5B1019+Mo%5D",
        Directed:"David Ayer",
        year:"2024",
        dure:"105m"
    },
    {
        id: Math.random(),
        title: " Badland Hunters",
        image:
        "https://image.tmdb.org/t/p/w342/24CL0ySodCF8bcm38xtBeHzHp7W.jpg",
        rate: 6.8,
        decr: "After a deadly earthquake turns Seoul into a lawless badland, a fearless huntsman springs into action to rescue a teenager abducted by a mad doctor.",
        Starring:"Ma Dong-seok, Lee Hee-jun, Lee Jun-young, Roh Jeong-eui, Ahn Ji-hye, Park Ji-hoon, Jang Young-nam, Park Hyo-joon, Seong Byeong-suk, Jung Young-ju",
        stream:"https://youtu.be/hKbo-ZKdSqw" ,
        lang: "EN",
        genre: "action",
        downlaod: "https://stellaruranus.com/?utm_medium=Special_Interest&utm_source=easyaffiliate&utm_campaign=1076&utm_content=LandingPage_Classic_Keyword&emid=65cb65b195182508e7088ba3&trs=65cb65b195182508e7088ba2&ext_publisher_id=1076&fn=The+Marvels+%5B1019+Mo%5D",
        Directed:"Heo Myeong-haeng",
        year:"2024",
        dure:"107m"
    },
    {
        id: Math.random(),
        title: " Sixty Minutes",
        image:
        "https://image.tmdb.org/t/p/w342/aajCqg315CoJPu1NmgPCkbRjnl6.jpg",
        rate: 7.0,
        decr: "Desperate to keep custody of his daughter, a mixed martial arts fighter abandons a big match and races across Berlin to attend her birthday party.",
        Starring:"Emilio Sakraya, Dennis Mojen, Marie Mouroum, Florian Schmidtke, Paul Wollin, Aristo Luis, Morik Heydo, Alain Blazevic, Harry Szovik, Árpád Antolik",
        stream:"https://youtu.be/hKbo-ZKdSqw" ,
        lang: "EN",
        genre: "action",
        downlaod: "https://stellaruranus.com/?utm_medium=Special_Interest&utm_source=easyaffiliate&utm_campaign=1076&utm_content=LandingPage_Classic_Keyword&emid=65cb65b195182508e7088ba3&trs=65cb65b195182508e7088ba2&ext_publisher_id=1076&fn=The+Marvels+%5B1019+Mo%5D",
        Directed:"Oliver Kienle",
        year:"2024",
        dure:"107m"
    },
    {
        id: Math.random(),
        title: "Freelance",
        image:
        "https://image.tmdb.org/t/p/w342/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg",
        rate: 6.6,
        decr: "An ex-special forces operative takes a job to provide security for a journalist as she interviews a dictator, but a military coup breaks out in the middle of the interview, they are forced to escape into the jungle where they must survive.",
        stream: "https://filelions.to/v/2j084znm7qsw",
        starrring:"John Cena, Alison Brie, Juan Pablo Raba, Alice Eve, Marton Csokas, Christian Slater, Julianne Arrieta, Molly McCann, Daniel Toro, Sebastián Eslava",
        lang:"EN",
        genre: "action",
        downlaod: "https://filelions.to/d/2j084znm7qsw",
        Directed:"Pierre Morel",
        year:"2023",
        dure:"108m"
    },    
    {
        id: Math.random(),
        title: "Silent Night",
        image:
        "https://image.tmdb.org/t/p/w342/nJCP1ZNTPKlZ7S0Kv3gbmuraAT4.jpg",
        rate: 6.6,
        decr: "A tormented father witnesses his young son die when caught in a gang's crossfire on Christmas Eve. While recovering from a wound that costs him his voice, he makes vengeance his life's mission and embarks on a punishing training regimen in order to avenge his son's death.",
        stream: "https://filelions.to/v/2j084znm7qsw",
        starrring:"Joel Kinnaman, Kid Cudi, Harold Torres, Catalina Sandino Moreno, Valeria Santaella, Vinny O'Brien, Acoyani Chacon, Alejandro De Los Monteros, Angeles Woo, Robert 'Rock' Galotti",
        lang: "EN",
        genre: "action",
        downlaod: "https://filelions.to/d/2j084znm7qsw",
        Directed:"John Woo",
        year:"2023",
        dure:"104m"
    },
    {
        id: Math.random(),
        title: "Expend4bles",
        image:
        "https://image.tmdb.org/t/p/w342/iwsMu0ehRPbtaSxqiaUDQB9qMWT.jpg",
        rate: 6.4,
        decr: "Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.",
        stream: "https://filelions.to/v/2j084znm7qsw",
        starrring:"Jason Statham, Sylvester Stallone, 50 Cent, Megan Fox, Dolph Lundgren, Randy Couture, Iko Uwais, Andy García, Tony Jaa, Jacob Scipio",
        lang: "EN",
        genre: "action",
        downlaod: "https://filelions.to/d/2j084znm7qsw",
        Directed:"Scott Waugh",
        year:"2023",
        dure:"103m"
    }, 
    {
            id: Math.random(),
            title: "Due Justice",
            image:
            "https://image.tmdb.org/t/p/w342/35Uef7fz9ctYbJLXbJBCqvtttEQ.jpg",
            rate: 6.8,
            decr: "Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.",
            stream: "https://filelions.to/v/2j084znm7qsw",
            starrring:"Jason Statham, Sylvester Stallone, 50 Cent, Megan Fox, Dolph Lundgren, Randy Couture, Iko Uwais, Andy García, Tony Jaa, Jacob Scipio",
            lang: "EN",
            genre: "action",
            downlaod: "https://filelions.to/d/2j084znm7qsw",
            Directed:"Scott Waugh",
            year:"2023",
            dure:"98m"
    }, 
    {
            id:Math.random(),
            title:"Venom",
            image:"https://image.tmdb.org/t/p/w342/2uNW4WbgBXL25BAbXGLnLqX71Sw.jpg",
            rate:6.8,
            decr:"Investigative journalist Eddie Brock attempts a comeback following a scandal, but accidentally becomes the host of Venom, a violent, super powerful alien symbiote. Soon, he must rely on his newfound powers to protect the world from a shadowy organization looking for a symbiote of their own.",
            Starring:"Tom Hardy, Michelle Williams, Riz Ahmed, Scott Haze, Reid Scott, Jenny Slate, Melora Walters, Woody Harrelson, Peggy Lu, Malcolm C. Murray",
            stream:"https://movieus.fun/themes/v1//assets/movie.mp4",
            lang:"EN",
            genre:"action",
            downlaod:"https://movieus.fun/en/loading?id=982940&title=Due%20Justice&action=register",
            Directed:"Ruben Fleischer",
            year:"2023",
            dure:"98m"
    },
        //Adventure Movies
    {
        id: Math.random(),
        title: "Aquaman and the Lost Kingdom",
        image:
        "https://image.tmdb.org/t/p/w342/7lTnXOy0iNtBAdRP3TZvaKJ77F6.jpg",
        rate: 6.9,
        decr: "Black Manta seeks revenge on Aquaman for his father's death. Wielding the Black Trident's power, he becomes a formidable foe. To defend Atlantis, Aquaman forges an alliance with his imprisoned brother. They must protect the kingdom.",
        Starring:"Jason Momoa, Patrick Wilson, Yahya Abdul-Mateen II, Randall Park, Amber Heard, Nicole Kidman, Dolph Lundgren, Temuera Morrison, Indya Moore, Pilou Asbæk",
        stream:"https://youtu.be/SzINZZ6iqxY?t=1" ,
        lang: "EN",
        genre: "Adventure",
        downlaod: "https://stellaruranus.com/?utm_medium=Special_Interest&utm_source=easyaffiliate&utm_campaign=1076&utm_content=LandingPage_Classic_Keyword&emid=65cb65b195182508e7088ba3&trs=65cb65b195182508e7088ba2&ext_publisher_id=1076&fn=The+Marvels+%5B1019+Mo%5D",
        Directed:"James Wan",
        year:"2023",
        dure:"124m"
    },
    {
        id:Math.random(),
        title:"Avatar: The Way of Water",
        image:"https://image.tmdb.org/t/p/w342/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
            rate:7.6,
            decr:"Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
            Starring:"Sam Worthington, Zoe Saldaña, Sigourney Weaver, Stephen Lang, Kate Winslet, Cliff Curtis, Joel David Moore, CCH Pounder, Edie Falco, Jemaine Clement",
            stream:"https://movieus.fun/themes/v1//assets/movie.mp4",
            lang:"EN",
            genre:"Adventure",
            downlaod:"https://movieus.fun/en/loading?id=76600&title=Avatar%3A%20The%20Way%20of%20Water&action=register",
            Directed:"James Cameron",
            year:"2022",
            dure:"192m"
        },
        {
            id:Math.random(),
            title:"Puss in Boots: The Last Wish",
            image:"https://image.tmdb.org/t/p/w342/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
            rate:8.3,
            decr:"Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
            Starring:"Antonio Banderas, Salma Hayek Pinault, Harvey Guillén, Wagner Moura, Florence Pugh, Olivia Colman, Ray Winstone, Samson Kayo, John Mulaney, Da'Vine Joy Randolph",
            stream:"https://movieus.fun/themes/v1//assets/movie.mp4",
            lang:"EN",
            genre:"Adventure",
            downlaod:"https://movieus.fun/en/loading?id=315162&title=Puss%20in%20Boots%3A%20The%20Last%20Wish&action=register",
            Directed:"Joel Crawford",
            year:"2022",
            dure:"103m"
        },
        {
            id:Math.random(),
            title:"The Animal Kingdom",
            image:"https://image.tmdb.org/t/p/w342/39AiQnXlXOjoqBSkiUpTG80rXLw.jpg",
            rate:7.3,
            decr:"In a world hit by a wave of mutations transforming humans into animals, François does everything he can to save his wife. As some of the creatures disappear into a nearby forest, he and their son Émile embark on a quest that will change their lives forever.",
            Starring:"Romain Duris, Paul Kircher, Adèle Exarchopoulos, Tom Mercier, Billie Blain, Xavier Aubert, Saadia Bentaïeb, Gabriel Caballero, Iliana Khelifa, Paul Muguruza",
            stream:"https://movieus.fun/themes/v1//assets/movie.mp4",
            lang:"EN",
            genre:"Adventure",
            downlaod:"https://movieus.fun/en/loading?id=943134&title=Le%20R%C3%A8gne%20animal&action=register",
            Directed:"Thomas Cailley",
            year:"2023",
            dure:"127m"
        },
        {
            id:Math.random(),
            title:"Dune",
            image:"https://image.tmdb.org/t/p/w342/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
            rate:7.8,
            decr:"Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
            Starring:"Timothée Chalamet, Rebecca Ferguson, Oscar Isaac, Josh Brolin, Stellan Skarsgård, Dave Bautista, Sharon Duncan-Brewster, Stephen McKinley Henderson, Zendaya, Chang Chen",
            stream:"https://movieus.fun/themes/v1//assets/movie.mp4",
            lang:"EN",
            genre:"Adventure",
            downlaod:"https://movieus.fun/en/loading?id=438631&title=Dune&action=register",
            Directed:"Denis Villeneuve",
            year:"2021",
            dure:"155m"
        },
        //Comedy Movies
        {
            id:Math.random(),
            title:"Wonka",
            image:"https://image.tmdb.org/t/p/w342/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
            rate:7.2,
            decr:"Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
            Starring:"Timothée Chalamet, Calah Lane, Keegan-Michael Key, Hugh Grant, Paterson Joseph, Olivia Colman, Tom Davis, Jim Carter, Rowan Atkinson, Matt Lucas",
            stream:"",
            lang:"EN",
            genre:"Comedy",
            downlaod:"",
            Directed:"Paul King",
            year:"2023",
            dure:"127m"
        },
        {
            id:Math.random(),
            title:"Migration",
            image:"https://image.tmdb.org/t/p/w342/ldfCF9RhR40mppkzmftxapaHeTo.jpg",
            rate:7.7,
            decr:"After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.",
            Starring:" Kumail Nanjiani, Elizabeth Banks, Caspar Jennings, Tresi Gazal, Awkwafina, Carol Kane, Keegan-Michael Key, Danny DeVito, David Mitchell, Isabela Merced",
            stream:"",
            lang:"EN",
            genre:"Comedy",
            downlaod:"",
            Directed:"Benjamin Renner",
        },
        {
            id:Math.random(),
            title:"Anyone But You",
            image:"https://image.tmdb.org/t/p/w342/yRt7MGBElkLQOYRvLTT1b3B1rcp.jpg",
            rate:7.1,
            decr:"After an amazing first date, Bea and Ben’s fiery attraction turns ice cold — until they find themselves unexpectedly reunited at a destination wedding in Australia. So they do what any two mature adults would do: pretend to be a couple.",
            Starring:"Sydney Sweeney, Glen Powell, Alexandra Shipp, Michelle Hurd, Bryan Brown, Darren Barnet, Hadley Robinson, Dermot Mulroney, Rachel Griffiths, GaTa",
            stream:"",
            lang:"EN",
            genre:"Comedy",
            downlaod:"",
            Directed:"Will Gluck",
        },
        {
            id:Math.random(),
            title:"Argylle",
            image:"https://image.tmdb.org/t/p/w342/siduVKgOnABO4WH4lOwPQwaGwJp.jpg",
            rate:6.2,
            decr:"When the plots of reclusive author Elly Conway's fictional espionage novels begin to mirror the covert actions of a real-life spy organization, quiet evenings at home become a thing of the past. Accompanied by her cat Alfie and Aiden, a cat-allergic spy, Elly races across the world to stay one step ahead of the killers as the line between Conway's fictional world and her real one begins to blur.",
            Starring:"Bryce Dallas Howard, Sam Rockwell, Bryan Cranston, Catherine O'Hara, Henry Cavill, Dua Lipa, Ariana DeBose, John Cena, Samuel L. Jackson, Sofia Boutella",
            stream:"",
            lang:"EN",
            genre:"comedy",
            downlaod:"",
            Directed:"Matthew Vaughn",
        },
        {
            id:Math.random(),
            title:"The Underdoggs",
            image:"https://image.tmdb.org/t/p/w342/wj1VRcVsh39nkxLkZP8tuGd96tc.jpg",
            rate:6.1,
            decr:"Jaycen 'Two Js' Jennings is a washed-up former pro football star who has hit rock bottom. When sentenced to community service coaching the Underdoggs, an unruly pee-wee football team in his hometown, he sees it mostly as an opportunity to rebuild his public image. But in the process, he may just turn his life around and rediscover his love of the game.",
            Starring:"Snoop Dogg, Tika Sumpter, Elias Ferguson, Jonigan Booth, Caleb Dixon, Adan James Carrillo, Alexander Michael Gordon, Kylah Davila, Mike Epps, George Lopez",
            stream:"",
            lang:"EN",
            genre:"comedy",
            downlaod:"",
            Directed:"Charles Stone III",
        },
        //Horror Movies 

        {
            id:Math.random(),
            title:"Skal - Fight for Survival",
            image:"https://image.tmdb.org/t/p/w342/uQkiDKQyun13mqsOXv7I5MRKr0q.jpg",
            rate:6.1,
            decr:"My name's Arthur, a huge Internet star who's just hit 3 million subs. While in the midst of throwing an epic party to celebrate, the universe had the balls to bring on the effing apocalypse and cut my night short. What was supposed to be a perfect hangover, has turned into an epic fight for survival.",
            Starring:"Evan Marsh, Chris Sandiford, Mariah Inger, Darren Eisenhauer, Olivia Scriven, Trevor Hayes",
            stream:"",
            lang:"EN",
            genre:"Horror",
            downlaod:"",
            Directed:"Benjamin Cappelletti",
        },
        {
            id:Math.random(),
            title:"Meg 2: The Trench",
            image:"https://image.tmdb.org/t/p/w342/4m1Au3YkjqsxF8iwQy0fPYSxE0h.jpg",
            rate:6.6,
            decr:"An exploratory dive into the deepest depths of the ocean of a daring research team spirals into chaos when a malevolent mining operation threatens their mission and forces them into a high-stakes battle for survival.",
            Starring:"Jason Statham, Wu Jing, Shuya Sophia Cai, Page Kennedy, Sergio Peris-Mencheta, Sienna Guillory, Cliff Curtis, Skyler Samuels, Melissanthi Mahut, Whoopie van Raam",
            stream:"",
            lang:"EN",
            genre:"Horror",
            downlaod:"",
            Directed:"Ben Wheatley",
        },
        {
            id:Math.random(),
            title:"The Nun II",
            image:"https://image.tmdb.org/t/p/w342/5gzzkR7y3hnY8AD1wXjCnVlHba5.jpg",
            rate:6.8,
            decr:"In 1956 France, a priest is violently murdered, and Sister Irene begins to investigate. She once again comes face-to-face with a powerful evil.",
            Starring:"Taissa Farmiga, Jonas Bloquet, Storm Reid, Anna Popplewell, Bonnie Aarons, Katelyn Rose Downey, Suzanne Bertish, Léontine d'Oncieu, Anouk Darwin Homewood, Peter Hudson",
            stream:"",
            lang:"EN",
            genre:"Horror",
            downlaod:"",
            Directed:"Michael Chaves",
        },
        {
            id:Math.random(),
            title:"The Resort",
            image:"https://image.tmdb.org/t/p/w342/bXZUVJP8Fr3RId7SSsV4RXvjnIh.jpg",
            rate:5.3,
            decr:"Bianca Haase, Brock O'Hurn, Michael Vlamis, Michelle Randolph, Dave Sheridan, Dante Jimenez, Romualdo Castillo, Rodney Gemberling, Richard Teston, Andy Bumatai",
            Starring:"",
            stream:"",
            lang:"EN",
            genre:"Horror",
            downlaod:"",
            Directed:"Taylor Chien",
        },
        {
            id:Math.random(),
            title:"Baghead",
            image:"https://image.tmdb.org/t/p/w342/puVo9pxrL7OtwVHtkroCtXswlkb.jpg",
            rate:7.6,
            decr:"Following the death of her estranged father, Iris learns she has inherited a run-down, centuries-old pub. She travels to Berlin to identify her father’s body and meet with The Solicitor to discuss the estate. Little does she know, when the deed is signed she will become inextricably tied to an unspeakable entity that resides in the pub’s basement – Baghead – a shape-shifting creature that can transform into the dead.",
            Starring:"Freya Allan, Jeremy Irvine, Ruby Barker, Peter Mullan, Anne Müller, Svenja Jung, Ned Dennehy, Julika Jenkins, Saffron Burrows, Felix Römer",
            stream:"",
            lang:"EN",
            genre:"Horror",
            downlaod:"",
            Directed:"Alberto Corredor",
        },

        {
            id:Math.random(),
            title:"M3GAN",
            image:"https://image.tmdb.org/t/p/w342/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg",
            rate:7.1,
            decr:"A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
            Starring:" Allison Williams, Violet McGraw, Ronny Chieng, Amie Donald, Jenna Davis, Brian Jordan Alvarez, Jen Van Epps, Stephane Garneau-Monten, Lori Dungey, Amy Usherwood",
            stream:"",
            lang:"EN",
            genre:"Horror",
            downlaod:"",
            Directed:"Gerard Johnstone",
        },
        {
            id:Math.random(),
            title:"Five Nights at Freddy's",
            image:"https://image.tmdb.org/t/p/w342/7BpNtNfxuocYEVREzVMO75hso1l.jpg",
            rate:7.7,
            decr:"Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.",
            Starring:"Josh Hutcherson, Piper Rubio, Elizabeth Lail, Matthew Lillard, Mary Stuart Masterson, Kat Conner Sterling, David Lind, Christian Stokes, Joseph Poliquin, Grant Feely",
            stream:"",
            lang:"EN",
            genre:"Horror",
            downlaod:"",
            Directed:"Emma Tammi",
        },
        //war movies 
        {
            id:Math.random(),
            title:"Guy Ritchie's The Covenant",
            image:"https://image.tmdb.org/t/p/w342/kVG8zFFYrpyYLoHChuEeOGAd6Ru.jpg",
            rate:7.8,
            decr:"During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of grueling terrain.",
            Starring:"Jake Gyllenhaal, Dar Salim, Sean Sagar, Jason Wong, Rhys Yates, Christian Ochoa, Bobby Schofield, Emily Beecham, Jonny Lee Miller, Alexander Ludwig",
            stream:"",
            lang:"EN    ",
            genre:"War",
            downlaod:"",
            Directed:"Guy Ritchie",
        },
        {
            id:Math.random(),
            title:"Napoleon",
            image:"https://image.tmdb.org/t/p/w342/vcZWJGvB5xydWuUO1vaTLI82tGi.jpg",
            rate:6.5,
            decr:"An epic that details the checkered rise and fall of French Emperor Napoleon Bonaparte and his relentless journey to power through the prism of his addictive, volatile relationship with his wife, Josephine.",
            Starring:"Joaquin Phoenix, Vanessa Kirby, Tahar Rahim, Rupert Everett, Mark Bonnar, Paul Rhys, Ben Miles, Riana Duce, Ludivine Sagnier, Edouard Philipponnat",
            stream:"",
            lang:"EN",
            genre:"war",
            downlaod:"",
            Directed:"Ridley Scott",
        },
        {
            id:Math.random(),
            title:"All Quiet on the Western Front",
            image:"https://image.tmdb.org/t/p/w342/2IRjbi9cADuDMKmHdLK7LaqQDKA.jpg",
            rate:7.7,
            decr:"Paul Baumer and his friends Albert and Muller, egged on by romantic dreams of heroism, voluntarily enlist in the German army. Full of excitement and patriotic fervour, the boys enthusiastically march into a war they believe in. But once on the Western Front, they discover the soul-destroying horror of World War I.",
            Starring:"Felix Kammerer, Albrecht Schuch, Aaron Hilmer, Moritz Klaus, Adrian Grünewald, Edin Hasanović, Daniel Brühl, Thibault de Montalembert, Devid Striesow, Andreas Döhler",
            stream:"",
            lang:"EN",
            genre:"war",
            downlaod:"",
            Directed:"Edward Berger",
        },
        //Documentary movies
        {
            id:Math.random(),
            title:"Choose to Believe",
            image:"https://image.tmdb.org/t/p/w342/eLbDSu14EZ2VldIgDDGrt5pJkoL.jpg",
            rate:10,
            decr:"It narrates the epic title obtained by the Argentine National Team in the World Cup Qatar 2022 with testimonies of the protagonists, told from the intimacy and in first person.",
            Starring:"Ricardo Darín, Lionel Scaloni, Lionel Messi, Ángel Di María, Julián Álvarez, Rodrigo De Paul, Emiliano Martínez, Nahuel Molina, Enzo Fernández, Nicolás Otamendi",
            stream:"",
            lang:"EN",
            genre:"Documentary",
            downlaod:"",
            Directed:"Martín Méndez, Gonzalo Arias",
        },
        {
            id:Math.random(),
            title:"Society of the Snow: Who Were We on the Mountain? ",
            image:"https://image.tmdb.org/t/p/w342/6TGDsFSSi0dvpcwZsjUj6LxtPY2.jpg",
            rate:7.6,
            decr:"An in-depth look at the creative process behind Society of the Snow, featuring cast, crew, director J.A. Bayona and even real-life survivors.",
            Starring:"",
            stream:"",
            lang:"EN",
            genre:"Documentary",
            downlaod:"",
            Directed:"Manuel Romo",
        }, 
        //Animation movies 
        {
            id:Math.random(),
            title:"Wish",
            image:"https://image.tmdb.org/t/p/w342/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg",
            rate:6.7,
            decr:"Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.",
            Starring:"Ariana DeBose, Chris Pine, Alan Tudyk, Angelique Cabral, Victor Garber, Natasha Rothwell, Jennifer Kumiyama, Harvey Guillén, Niko Vargas, Evan Peters",
            stream:"",
            lang:"EN",
            genre:"Animation",
            downlaod:"",
            Directed:"Chris Buck, Fawn Veerasunthorn",
        },
        {
            id:Math.random(),
            title:"Orion and the Dark",
            image:"https://image.tmdb.org/t/p/w342/N2ddXhBX5kqwA9flbm2yqFtX6b.jpg",
            rate:6.8,
            decr:"A boy with an active imagination faces his fears on an unforgettable journey through the night with his new friend: a giant, smiling creature named Dark.",
            Starring:"Jacob Tremblay, Paul Walter Hauser, Angela Bassett, Colin Hanks, Natasia Demetriou, Golda Rosheuvel, Nat Faxon, Aparna Nancherla, Ike Barinholtz, Carla Gugino",
            stream:"",
            lang:"EN",
            genre:"Animation",
            downlaod:"",
            Directed:"Sean Charmatz",
        },
        {
            id:Math.random(),
            title:"Despicable Me 4",
            image:"https://image.tmdb.org/t/p/w342/aun2IpLDx2E08hYj8xnAEUEFLlo.jpg",
            rate:8.4,
            decr:"Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, and the family is forced to go on the run.",
            Starring:"Steve Carell, Kristen Wiig, Will Ferrell, Sofía Vergara, Joey King, Stephen Colbert, Chloe Fineman, Miranda Cosgrove, Dana Gaier, Madison Polan",
            stream:"",
            lang:"EN",
            genre:"Animation",
            downlaod:"",
            Directed:"Chris Renaud",
        },
        {
            id:Math.random(),
            title:"PAW Patrol: The Mighty Movie",
            image:"https://image.tmdb.org/t/p/w342/aTvePCU7exLepwg5hWySjwxojQK.jpg",
            rate:7.1,
            decr:"A magical meteor crash lands in Adventure City and gives the PAW Patrol pups superpowers, transforming them into The Mighty Pups.",
            Starring:"Mckenna Grace, Christian Convery, Taraji P. Henson, Kristen Bell, Lil Rel Howery, James Marsden, Finn Lee-Epp, Serena Williams, Alan Kim, Brice Gonzalez",
            stream:"",
            lang:"EN",
            genre:"Animation",
            downlaod:"",
            Directed:"Cal Brunker",
        },
        //Drama movies
        {
            id:Math.random(),
            title:"My Fault",
            image:"https://image.tmdb.org/t/p/w342/w46Vw536HwNnEzOa7J24YH9DPRS.jpg",
            rate:8.0,
            decr:"Noah must leave her city, boyfriend, and friends to move into William Leister's mansion, the flashy and wealthy husband of her mother Rafaela. As a proud and independent 17 year old, Noah resists living in a mansion surrounded by luxury. However, it is there where she meets Nick, her new stepbrother, and the clash of their strong personalities becomes evident from the very beginning.",
            Starring:"Nicole Wallace, Gabriel Guevara, Marta Hazas, Iván Sánchez, Eva Ruiz, Víctor Varona, Fran Berenguer, Adriana Ubani, Iván Massagué, Mariano Venancio",
            stream:"",
            lang:"EN",
            genre:"Drama",
            downlaod:"",
            Directed:"Domingo González",
        },
        {
            id:Math.random(),
            title:"Through My Window: Across the Sea",
            image:"https://image.tmdb.org/t/p/w342/hisRiTK0zCP1sXtlCSrmFRVOVlz.jpg",
            rate:6.4,
            decr:"After a year of long-distance, Raquel and Ares reunite on a steamy beach trip. Faced with fresh flirtations and insecurities, will their love prevail?",
            Starring:"Clara Galle, Julio Peña, Guillermo Lasheras, Natalia Azahara, Hugo Arbues, Eric Masip, Andrea Chaparro, Emilia Lazo, Ivan Lapadula, Carla Tous",
            stream:"",
            lang:"EN",
            genre:"Drama",
            downlaod:"",
            Directed:"Marçal Forés",
        },
        {
            id:Math.random(),
            title:"Killers of the Flower Moon",
            image:"https://image.tmdb.org/t/p/w342/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
            rate:7.6,
            decr:"When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.",
            Starring:" Leonardo DiCaprio, Lily Gladstone, Robert De Niro, Jesse Plemons, Scott Shepherd, Cara Jade Myers, JaNae Collins, William Belleau, Jason Isbell, Louis Cancelmi",
            stream:"",
            lang:"EN",
            genre:"Drama",
            downlaod:"",
            Directed:"Martin Scorsese",
        }, 
        //fantasy movies
        {
            id:Math.random(),
            title:"Harry Potter and the Philosopher's Stone",
            image:"https://image.tmdb.org/t/p/w342/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg",
            rate:7.9,
            decr:"Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths—and about the villain who's to blame",
            Starring:"Daniel Radcliffe, Rupert Grint, Emma Watson, Richard Harris, Tom Felton, Alan Rickman, Robbie Coltrane, Maggie Smith, Richard Griffiths, Ian Hart",
            stream:"",
            lang:"EN",
            genre:"Fantasy",
            downlaod:"",
            Directed:"Chris Columbus",
        },
        {
            id:Math.random(),
            title:"maboroshi",
            image:"https://image.tmdb.org/t/p/w342/7kzoPEasqFZGPGHj1imsLtTM20k.jpg",
            rate:7.7,
            decr:"A factory explosion plunges a small town into a timeless freeze, leaving teenage Masamune and his pals to grapple with a quickly collapsing reality.",
            Starring:"Junya Enoki, Reina Ueda, Misaki Kuno, Koji Seto, Kento Hayashi, Taku Yashiro, Tasuku Hatanaka, Daiki Kobayashi, Ayaka Saito, Maki Kawase",
            stream:"",
            lang:"EN",
            genre:"Fantasy",
            downlaod:"",
            Directed:"Mari Okada",
        },
        {
            id:Math.random(),
            title:"Erik Stoneheart ",
            image:"https://image.tmdb.org/t/p/w342/38Sq6aBAwx3hmUAuuyqZu8AjH3Y.jpg",
            rate:4.0,
            decr:"Erik is convinced he has a stone for a heart. That’s why he doesn’t mind that his parents have no time for him, or that he is bullied at school, or that he has no real friends. When his family moves to a villa they inherited, he is confronted by Maria whom Erik's parents want to kick out along with her father. Maria refuses to move and promises to make Erik's life a living hell. As a last attempt to defeat Erik, Maria goes to look for her mother who disappeared two years ago. Together they end up on a fantastical journey to the In-Between-World and Erik learns how hard it really is to wear a heart of stone.",
            Starring:"Herman Avandi, Florin Gussak, Juhan Ulfsak, Laura Peterson-Aardam, Jules Werner, Kristjan Sarv, Anti Reinthal, Renārs Kaupers, Nero Urke, Hendrik Toompere Jr. Jr.",
            stream:"",
            lang:"EN",
            genre:"Fantasy",
            downlaod:"",
            Directed:"Ilmar Raag",
        }, 
        // Mystery Movies
        {
            id:Math.random(),
            title:"The Engineer ",
            image:"https://image.tmdb.org/t/p/w342/t2WBlN3YCzieAezM3n3Oh20Ue2s.jpg",
            rate:5.2,
            decr:"As Israel is rocked by a series of terrorist bombings, a US senator's daughter is killed in one bloody explosion. Now, ex-Mossad agent Etan must lead an elite, covert team of agents and mercenaries to find the man responsible—the elusive “Engineer.” Can they find and destroy the madman before more innocent lives are lost?",
            Starring:"Emile Hirsch, Danny A. Abeckaser, Tsahi Halevi, Angel Bonanni, Yarden Toussia-Cohen, Oshri Cohen, Adam Haloon, Lee Keinan, Omer Hazan, Robert Davi",
            stream:"",
            lang:"EN",
            genre:"Mystery",
            downlaod:"",
            Directed:"Danny A. Abeckaser",
        }, 
        {
            id:Math.random(),
            title:"The Batman",
            image:"https://image.tmdb.org/t/p/w342/74xTEgt7R36Fpooo50r9T25onhq.jpg",
            rate:7.7,
            decr:"In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler",
            Starring:"Robert Pattinson, Zoë Kravitz, Paul Dano, Jeffrey Wright, John Turturro, Peter Sarsgaard, Andy Serkis, Colin Farrell, Jayme Lawson, Gil Perez-Abraham",
            stream:"",
            lang:"EN",
            genre:"Mystery",
            downlaod:"",
            Directed:" Matt Reeves",
        }, 

] 
export default dataMovies;